name: Gitleaks Scan

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  gitleaks:
    name: Scan for secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: >
            detect
            --redact
            --report-format sarif
            --report-path results.sarif
            --exit-code 1
